// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHVMdywY3QmI37r4FJICET8QyB6yK1jo',
    appId: '1:725513144393:web:a6cac4b836db7b2d83d798',
    messagingSenderId: '725513144393',
    projectId: 'fir-flutter-ac480',
    authDomain: 'fir-flutter-ac480.firebaseapp.com',
    storageBucket: 'fir-flutter-ac480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fSk8foalCDEgcspziDjrSMcWqaX22ps',
    appId: '1:725513144393:android:4c4c0db1375af47783d798',
    messagingSenderId: '725513144393',
    projectId: 'fir-flutter-ac480',
    storageBucket: 'fir-flutter-ac480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDejXGG0Jpg8WjRUU-yF6z9OYEtaAFOGKw',
    appId: '1:725513144393:ios:061dd0317e23079883d798',
    messagingSenderId: '725513144393',
    projectId: 'fir-flutter-ac480',
    storageBucket: 'fir-flutter-ac480.appspot.com',
    iosBundleId: 'com.example.sgtransport',
  );
}
